### ISSUE TITLE
Incomplete type annotations

### ISSUE THREAD

**Issue by rohithill** [rohithill/nith_result_cli#4]
In the file `nith_result.py` type annotations are incomplete. It'll be great to have more type annotations.

**Comment by noturshek** [comment]
Hi @rohithill,

I have read your issue and also read your codes and I think it will be great to help this project by adding type annotations wherever possible. I would like to contribute to the project by resolving the issue.

Please do assign me this issue and I will start working on the issue as soon as I get assigned.

Best,
Abhishek

**Comment by noturshek** [comment]
Hi @rohithill,

Please let me know if more changes need to be made.

Best,
Abhishek
